import { createContext, useContext, useState, useCallback } from 'react';

// =============================================
// App Context — global state
// =============================================

const AppContext = createContext(null);

export function AppProvider({ children }) {
  // Toast notifications
  const [toasts, setToasts] = useState([]);
  // Notification panel
  const [notifications] = useState([
    { id: 1, text: '3 new volunteer applications received', time: '5 min ago', read: false, icon: '🤝' },
    { id: 2, text: "Prema's Birthday campaign reached 75% goal!", time: '1 hr ago', read: false, icon: '🎉' },
    { id: 3, text: 'CSR partner viewed Digital Skills Challenge', time: '2 hrs ago', read: true, icon: '🏢' },
    { id: 4, text: 'Field report summary generated by HOPE AI', time: '3 hrs ago', read: true, icon: '🤖' },
    { id: 5, text: 'New skill volunteer: Ananya Sharma (Python)', time: 'Yesterday', read: true, icon: '💡' },
  ]);

  // Global campaign state (for donation simulation)
  const [campaignData, setCampaignData] = useState({
    name: "Prema's Birthday for Education",
    goal: 25000,
    raised: 18750,
    supporters: 42,
    occasion: 'Birthday',
    cause: 'Education',
    message: "On my birthday, I'm raising funds to help 50 children access quality education. Every rupee makes a difference!",
  });

  const addToast = useCallback((toast) => {
    const id = Date.now();
    setToasts(prev => [...prev, { ...toast, id }]);
    setTimeout(() => {
      setToasts(prev => prev.filter(t => t.id !== id));
    }, 4500);
  }, []);

  const removeToast = useCallback((id) => {
    setToasts(prev => prev.filter(t => t.id !== id));
  }, []);

  const donate = useCallback((amount) => {
    setCampaignData(prev => ({
      ...prev,
      raised: prev.raised + amount,
      supporters: prev.supporters + 1,
    }));
  }, []);

  return (
    <AppContext.Provider value={{
      toasts, addToast, removeToast,
      notifications,
      campaignData, donate,
    }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}
